# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Pro.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1103, 752)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 2, 2, 1, 1)
        self.ready_received = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ready_received.setFont(font)
        self.ready_received.setObjectName("ready_received")
        self.gridLayout.addWidget(self.ready_received, 4, 0, 1, 1)
        self.data_edit2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_edit2.sizePolicy().hasHeightForWidth())
        self.data_edit2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.data_edit2.setFont(font)
        self.data_edit2.setObjectName("data_edit2")
        self.gridLayout.addWidget(self.data_edit2, 1, 3, 1, 1)
        self.ready_send = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ready_send.sizePolicy().hasHeightForWidth())
        self.ready_send.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ready_send.setFont(font)
        self.ready_send.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ready_send.setObjectName("ready_send")
        self.gridLayout.addWidget(self.ready_send, 3, 0, 1, 1)
        self.data_edit1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_edit1.sizePolicy().hasHeightForWidth())
        self.data_edit1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.data_edit1.setFont(font)
        self.data_edit1.setObjectName("data_edit1")
        self.gridLayout.addWidget(self.data_edit1, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 2, 1, 1)
        self.show_receive = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_receive.sizePolicy().hasHeightForWidth())
        self.show_receive.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.show_receive.setFont(font)
        self.show_receive.setObjectName("show_receive")
        self.gridLayout.addWidget(self.show_receive, 4, 1, 1, 3)
        self.show_send = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_send.sizePolicy().hasHeightForWidth())
        self.show_send.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.show_send.setFont(font)
        self.show_send.setObjectName("show_send")
        self.gridLayout.addWidget(self.show_send, 3, 1, 1, 3)
        self.btn_send = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_send.sizePolicy().hasHeightForWidth())
        self.btn_send.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_send.setFont(font)
        self.btn_send.setObjectName("btn_send")
        self.gridLayout.addWidget(self.btn_send, 1, 4, 1, 1)
        self.clear_receive = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_receive.sizePolicy().hasHeightForWidth())
        self.clear_receive.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clear_receive.setFont(font)
        self.clear_receive.setObjectName("clear_receive")
        self.gridLayout.addWidget(self.clear_receive, 4, 4, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 4, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cmb_port_name = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmb_port_name.sizePolicy().hasHeightForWidth())
        self.cmb_port_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cmb_port_name.setFont(font)
        self.cmb_port_name.setObjectName("cmb_port_name")
        self.cmb_port_name.addItem("")
        self.cmb_port_name.addItem("")
        self.horizontalLayout.addWidget(self.cmb_port_name)
        self.btn_open = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_open.sizePolicy().hasHeightForWidth())
        self.btn_open.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_open.setFont(font)
        self.btn_open.setObjectName("btn_open")
        self.horizontalLayout.addWidget(self.btn_open)
        self.btn_close = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_close.sizePolicy().hasHeightForWidth())
        self.btn_close.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_close.setFont(font)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout.addWidget(self.btn_close)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButton1 = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton1.sizePolicy().hasHeightForWidth())
        self.radioButton1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton1.setFont(font)
        self.radioButton1.setObjectName("radioButton1")
        self.horizontalLayout_4.addWidget(self.radioButton1)
        self.radioButton_w = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_w.setFont(font)
        self.radioButton_w.setObjectName("radioButton_w")
        self.horizontalLayout_4.addWidget(self.radioButton_w)
        self.radioButton2 = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton2.sizePolicy().hasHeightForWidth())
        self.radioButton2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton2.setFont(font)
        self.radioButton2.setObjectName("radioButton2")
        self.horizontalLayout_4.addWidget(self.radioButton2)
        self.radioButton3 = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton3.sizePolicy().hasHeightForWidth())
        self.radioButton3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton3.setFont(font)
        self.radioButton3.setObjectName("radioButton3")
        self.horizontalLayout_4.addWidget(self.radioButton3)
        self.radioButton4 = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton4.sizePolicy().hasHeightForWidth())
        self.radioButton4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton4.setFont(font)
        self.radioButton4.setObjectName("radioButton4")
        self.horizontalLayout_4.addWidget(self.radioButton4)
        self.radioButton5 = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton5.sizePolicy().hasHeightForWidth())
        self.radioButton5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton5.setFont(font)
        self.radioButton5.setObjectName("radioButton5")
        self.horizontalLayout_4.addWidget(self.radioButton5)
        self.radioButton6 = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton6.setFont(font)
        self.radioButton6.setObjectName("radioButton6")
        self.horizontalLayout_4.addWidget(self.radioButton6)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.radioButton2.clicked.connect(self.data_edit1.clear)
        self.radioButton2.clicked.connect(self.data_edit2.clear)
        self.radioButton1.clicked.connect(self.data_edit1.clear)
        self.radioButton1.clicked.connect(self.data_edit2.clear)
        self.radioButton3.clicked.connect(self.data_edit1.clear)
        self.radioButton3.clicked.connect(self.data_edit2.clear)
        self.radioButton4.clicked.connect(self.data_edit1.clear)
        self.radioButton4.clicked.connect(self.data_edit2.clear)
        self.radioButton5.clicked.connect(self.data_edit1.clear)
        self.radioButton5.clicked.connect(self.data_edit2.clear)
        self.clear_receive.clicked.connect(self.show_receive.clear)
        self.radioButton_w.clicked.connect(self.data_edit1.clear)
        self.radioButton_w.clicked.connect(self.data_edit2.clear)
        self.pushButton.clicked.connect(self.show_send.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ready_received.setText(_translate("MainWindow", "       已接受："))
        self.ready_send.setText(_translate("MainWindow", "       已发送："))
        self.label.setText(_translate("MainWindow", "      方位"))
        self.label_2.setText(_translate("MainWindow", "     俯仰     "))
        self.btn_send.setText(_translate("MainWindow", "发送"))
        self.clear_receive.setText(_translate("MainWindow", "清空接收区"))
        self.pushButton.setText(_translate("MainWindow", "清空发送区"))
        self.cmb_port_name.setItemText(0, _translate("MainWindow", "COM1"))
        self.cmb_port_name.setItemText(1, _translate("MainWindow", "COM2"))
        self.btn_open.setText(_translate("MainWindow", "打开"))
        self.btn_close.setText(_translate("MainWindow", "关闭"))
        self.radioButton1.setText(_translate("MainWindow", "速度运行模式"))
        self.radioButton_w.setText(_translate("MainWindow", "稳定运行模式"))
        self.radioButton2.setText(_translate("MainWindow", "位置运行模式"))
        self.radioButton3.setText(_translate("MainWindow", "功放上电"))
        self.radioButton4.setText(_translate("MainWindow", "功放断电"))
        self.radioButton5.setText(_translate("MainWindow", "锁定"))
        self.radioButton6.setText(_translate("MainWindow", "取数指令"))

